import { createAccount, createClient } from "genlayer-js";
import { studionet } from "genlayer-js/chains";
import { TransactionStatus } from "genlayer-js/types";
import { readFileSync } from "node:fs";
const env=Object.fromEntries(readFileSync('.env.e2e','utf8').split(/\r?\n/).filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1)]}));
const a=createAccount(`0x${env.WALLET_A_PRIVATE_KEY}`),b=createAccount(`0x${env.WALLET_B_PRIVATE_KEY}`),read=createClient({chain:studionet,endpoint:env.RPC_URL}),wa=createClient({chain:studionet,endpoint:env.RPC_URL,account:a}),wb=createClient({chain:studionet,endpoint:env.RPC_URL,account:b}),address=env.CONTRACT_ADDRESS;
const base='https://gateway.pinata.cloud/ipfs/'; const ref=base+'QmTqXy36wxN5rNwtsSpPd1PjhTUMuHCybc7NFGVjZe4jcY?download=1', eq=base+'QmV5wyRT1UpmgrAB5UFQLcAmHoiT8tCmF6qgdJ5urg8WXV?download=1', chRef=base+'QmSq8wLCr4pJyFsBJ94d6HP9Ff5WgJA2ae5sFxdY5uF7wY?download=1', ch=base+'QmatxPYpvdbvrWH2utMh4eobcDXS9XqXJBJhoriSCdVpGb?download=1'; const hash='sha256:7f3b2d2a2d1f8c8f0c3b4f6a8e9d0b1c2a3e4f5b6c7d8e9f0011223344556677',nft='0x4444444444444444444444444444444444444444';
async function v(m,args){const x=await read.readContract({address,functionName:m,args,stateStatus:'accepted'});console.log(m,args.join(',')+' -> '+x);return String(x)} async function t(c,l,m,args){const h=await c.writeContract({address,functionName:m,args,value:0n});console.log(l+' tx '+h);const r=await read.waitForTransactionReceipt({hash:h,status:TransactionStatus.FINALIZED,retries:120,interval:3000,fullTransaction:true});const x=r.consensus_data?.leader_receipt?.[0]?.result?.payload?.readable||r.result_name||'UNKNOWN';console.log(l+' '+(r.statusName||'FINALIZED')+' result='+x);return {h,result:String(x)}}
const collection=BigInt((await v('get_counts',[])).split('|')[0]); await t(wa,'collection','register_collection',['Pinata Gateway Fixture','Ethereum mainnet',nft,base,ref,hash]); await t(wa,'freeze-collection','freeze_collection',[collection]); const s1=await t(wa,'snapshot-verified','register_snapshot',[collection,505n,ref,hash,'ipfs://bafybeiverifiedimagecid000000000000000000000000000000001',JSON.stringify({background:'Ink',edition:'1/1',palette:'Cobalt'})]); const s2=await t(wa,'snapshot-changed','register_snapshot',[collection,506n,chRef,hash,'ipfs://bafybeioriginalimagecid000000000000000000000000000000001',JSON.stringify({rarity:'Legendary',edition:'1/1',palette:'Gold'})]); const id1=BigInt(s1.result.match(/\d+/)[0]),id2=BigInt(s2.result.match(/\d+/)[0]); await t(wa,'freeze-verified','freeze_snapshot',[id1]); await t(wa,'freeze-changed','freeze_snapshot',[id2]); const start=BigInt((await v('get_counts',[])).split('|')[2]); await t(wb,'submit-verified','submit_verification',[id1,eq]); await t(wb,'submit-changed','submit_verification',[id2,ch]); const vr=await t(wa,'verify-verified','verify_metadata',[start]); const cr=await t(wb,'verify-changed','verify_metadata',[start+1n]); await v('get_verification',[start]); await v('get_verification',[start+1n]); console.log('RESULTS verified='+vr.result+' changed='+cr.result);
